export { default as About } from "./about";
export { default as Blog } from "./blog";
export { default as BlogEntry } from "./blogEntry";
export { default as Contact } from "./contact";
export { default as Landing } from "./landing";
export { default as MartialArtist } from "./martialarts";
export { default as Musician } from "./music";
export { default as NotFound } from "./notFound";
export { default as WebPortfolio } from "./webdev";