export { default as About } from "./about";
export { default as Contact } from "./contact";
export { default as Ecards } from "./ecards";
export { default as Games } from "./games";
export { default as Landing } from "./landing";
export { default as MartialArtist } from "./martialarts";
export { default as Musician } from "./music";
export { default as NotFound } from "./notFound";
export { default as Redirect} from './redirect';
export { default as WebPortfolio } from "./webdev";